// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/find-activities.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { activitiesData, goalMapping } from "npm:@/data/activities";
var AGE_VALUES = ["0-1", "1-3", "3-6", "6-10", "10+"];
var GOAL_VALUES = ["Calm Down", "Burn Energy", "Beat Boredom", "Connect", "Quiet Time"];
var find_activities_default = defineTool({
  name: "find_activities",
  title: "Find kids activities",
  description: "Search the WhatNow Kid activity bank for age-appropriate, mood-matched ideas. Filter by age range, goal, environment, cost, and parenting style. Returns up to `limit` matching activities.",
  inputSchema: {
    ages: z.array(z.enum(AGE_VALUES)).optional().describe("One or more child age ranges to match. Omit for any age."),
    goals: z.array(z.enum(GOAL_VALUES)).optional().describe("One or more parenting goals to match. Omit for any goal."),
    environment: z.enum(["Any", "Indoor", "Outdoor"]).optional().default("Any").describe("Where the activity takes place."),
    cost: z.enum(["Any", "Free", "Paid"]).optional().default("Any").describe("Whether the activity requires paid materials."),
    parenting: z.enum(["Hands On", "Hands Off"]).optional().describe("Parenting involvement level. Omit for either."),
    limit: z.number().int().min(1).max(50).optional().default(10).describe("Max activities to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ ages, goals, environment = "Any", cost = "Any", parenting, limit = 10 }) => {
    const matches = activitiesData.filter((a) => {
      if (ages && ages.length > 0 && !ages.some((age) => a.age.includes(age))) return false;
      if (goals && goals.length > 0) {
        const relevantMoods = goals.flatMap((g) => goalMapping[g]);
        if (!a.mood.some((m) => relevantMoods.includes(m))) return false;
      }
      if (environment !== "Any" && a.environment !== environment && a.environment !== "Both") return false;
      if (cost !== "Any" && a.cost !== cost) return false;
      if (parenting && a.parenting !== parenting) return false;
      return true;
    });
    const results = matches.slice(0, limit).map((a) => ({
      title: a.title,
      description: a.description,
      age: a.age,
      environment: a.environment,
      cost: a.cost,
      parenting: a.parenting,
      duration: a.duration,
      setupTime: a.setupTime,
      energyLevel: a.energyLevel,
      materials: a.materials
    }));
    return {
      content: [
        {
          type: "text",
          text: results.length === 0 ? "No activities matched those filters. Try relaxing one of them." : `Found ${matches.length} activity${matches.length === 1 ? "" : "s"}, returning ${results.length}:

` + results.map(
            (r, i) => `${i + 1}. ${r.title} (${r.age.join(", ")}, ${r.environment}, ${r.cost}, ${r.parenting}, ${r.duration})
   ${r.description}
   Materials: ${r.materials.join(", ")}`
          ).join("\n\n")
        }
      ],
      structuredContent: { total: matches.length, returned: results.length, activities: results }
    };
  }
});

// src/lib/mcp/tools/random-activity.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { activitiesData as activitiesData2, goalMapping as goalMapping2 } from "npm:@/data/activities";
var AGE_VALUES2 = ["0-1", "1-3", "3-6", "6-10", "10+"];
var GOAL_VALUES2 = ["Calm Down", "Burn Energy", "Beat Boredom", "Connect", "Quiet Time"];
var random_activity_default = defineTool2({
  name: "random_activity",
  title: "Pick a random kids activity",
  description: "Return one random WhatNow Kid activity idea, optionally narrowed by age, goal, environment, cost, or parenting style. Great for 'I'm feeling lucky' style prompts.",
  inputSchema: {
    ages: z2.array(z2.enum(AGE_VALUES2)).optional(),
    goals: z2.array(z2.enum(GOAL_VALUES2)).optional(),
    environment: z2.enum(["Any", "Indoor", "Outdoor"]).optional().default("Any"),
    cost: z2.enum(["Any", "Free", "Paid"]).optional().default("Any"),
    parenting: z2.enum(["Hands On", "Hands Off"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: ({ ages, goals, environment = "Any", cost = "Any", parenting }) => {
    const matches = activitiesData2.filter((a) => {
      if (ages && ages.length > 0 && !ages.some((age) => a.age.includes(age))) return false;
      if (goals && goals.length > 0) {
        const relevantMoods = goals.flatMap((g) => goalMapping2[g]);
        if (!a.mood.some((m) => relevantMoods.includes(m))) return false;
      }
      if (environment !== "Any" && a.environment !== environment && a.environment !== "Both") return false;
      if (cost !== "Any" && a.cost !== cost) return false;
      if (parenting && a.parenting !== parenting) return false;
      return true;
    });
    if (matches.length === 0) {
      return {
        content: [{ type: "text", text: "No activities matched those filters." }],
        isError: true
      };
    }
    const pick = matches[Math.floor(Math.random() * matches.length)];
    return {
      content: [
        {
          type: "text",
          text: `${pick.title}
${pick.description}

Age: ${pick.age.join(", ")} | ${pick.environment} | ${pick.cost} | ${pick.parenting}
Duration: ${pick.duration} | Setup: ${pick.setupTime} | Energy: ${pick.energyLevel}
Materials: ${pick.materials.join(", ")}`
        }
      ],
      structuredContent: {
        title: pick.title,
        description: pick.description,
        age: pick.age,
        environment: pick.environment,
        cost: pick.cost,
        parenting: pick.parenting,
        duration: pick.duration,
        setupTime: pick.setupTime,
        energyLevel: pick.energyLevel,
        materials: pick.materials
      }
    };
  }
});

// src/lib/mcp/tools/list-filters.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { activitiesData as activitiesData3 } from "npm:@/data/activities";
var list_filters_default = defineTool3({
  name: "list_filters",
  title: "List available filters",
  description: "Return the full set of filter values supported by the WhatNow Kid activity bank (age ranges, goals, environments, costs, parenting styles) plus the total activity count. Call this first if you're unsure what to pass to find_activities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      totalActivities: activitiesData3.length,
      ages: ["0-1", "1-3", "3-6", "6-10", "10+"],
      goals: ["Calm Down", "Burn Energy", "Beat Boredom", "Connect", "Quiet Time"],
      environments: ["Any", "Indoor", "Outdoor"],
      costs: ["Any", "Free", "Paid"],
      parenting: ["Hands On", "Hands Off"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "whatnow-kid-mcp",
  title: "WhatNow Kid",
  version: "0.1.0",
  instructions: "Instant kids activity ideas for parents and caregivers. Use `list_filters` to see the available filter values, `find_activities` to search the bank by age/goal/environment/cost/parenting style, and `random_activity` for a single lucky pick. All data is public; no auth required.",
  tools: [find_activities_default, random_activity_default, list_filters_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
